version: '3'
services:
  flask_app:
    build: .
    ports:
     - "5000:5000"

  mysql:
    image: percona:5.7.26-centos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: poizaq01
      MYSQL_DATABASE: BucketList
      MYSQL_USER: Flask
      MYSQL_PASSWORD: Fpass